version: '3.9'

services:
  front:
    image: sermalenk/skypro-front:lesson-37
    ports:
    - 80:80
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: $DB_HOST
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "8000:8000"
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: python3 manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_NAME: $DB_NAME
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: