# Generated by Django 4.0.1 on 2022-12-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.IntegerField(verbose_name='ID чата в телеграм'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_user_id',
            field=models.IntegerField(verbose_name='ID пользователя в телеграм'),
        ),
    ]
