# Generated by Django 4.0.1 on 2022-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.IntegerField(verbose_name='Код для верификации'),
        ),
    ]
