# Generated by Django 4.0.1 on 2022-12-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_tguser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
